services:

  netbox:
    image: netboxcommunity/netbox:${NETBOX_VERSION:-v4.5.8-4.0.2}
    environment:
      SUPERUSER_NAME: ${SUPERUSER_NAME:-admin}
      SUPERUSER_EMAIL: ${SUPERUSER_EMAIL:-admin@example.com}
      SUPERUSER_PASSWORD: ${SUPERUSER_PASSWORD:-Admin@1234567890}
      SKIP_SUPERUSER: "${SKIP_SUPERUSER:-false}"
      # O NetBox e o Django utilizam esta variável para
      # formatar datas e horas na interface web e no banco de dados.
      TIME_ZONE: "${TIME_ZONE:-America/Sao_Paulo}"
      # Banco de dados
      DB_HOST: ${DB_HOST:-postgres}
      DB_NAME: ${DB_NAME:-netbox}
      DB_USER: ${DB_USER:-netbox}
      DB_PASSWORD: ${DB_PASSWORD:-J5brHrAXFLQSif0K}
      # Redis (Task Queue)
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_DATABASE: ${REDIS_DATABASE:-0}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-H733Kdjndks81}
      # Redis (Cache)
      REDIS_CACHE_HOST: ${REDIS_CACHE_HOST:-redis-cache}
      REDIS_CACHE_DATABASE: ${REDIS_CACHE_DATABASE:-1}
      REDIS_CACHE_PASSWORD: ${REDIS_CACHE_PASSWORD:-t4Ph722qJ5QHeQ1qfu36}
      # Secret Key (gerada automaticamente se vazia)
      SECRET_KEY: ${SECRET_KEY:-}
      # Hosts permitidos (CRÍTICO para produção!)
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:-localhost 127.0.0.1 ::1}
    restart: unless-stopped
    ports:
      - "${NETBOX_PORT:-8000}:8080"
    healthcheck:
      start_period: 400s
      timeout: 30s
      interval: 30s
      retries: 5

  netbox-worker:
    image: netboxcommunity/netbox:${NETBOX_VERSION:-v4.5.8-4.0.2}
    environment:
      # Mesmas variáveis do netbox (necessárias para o worker)
      DB_HOST: ${DB_HOST:-postgres}
      DB_NAME: ${DB_NAME:-netbox}
      DB_USER: ${DB_USER:-netbox}
      DB_PASSWORD: ${DB_PASSWORD:-J5brHrAXFLQSif0K}
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_DATABASE: ${REDIS_DATABASE:-0}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-H733Kdjndks81}
      REDIS_CACHE_HOST: ${REDIS_CACHE_HOST:-redis-cache}
      REDIS_CACHE_DATABASE: ${REDIS_CACHE_DATABASE:-1}
      REDIS_CACHE_PASSWORD: ${REDIS_CACHE_PASSWORD:-t4Ph722qJ5QHeQ1qfu36}
      SECRET_KEY: ${SECRET_KEY:-}
      # Hosts permitidos (CRÍTICO para produção!)
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:-localhost 127.0.0.1 ::1}
    restart: unless-stopped

  postgres:
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-netbox}
      POSTGRES_USER: ${POSTGRES_USER:-netbox}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-J5brHrAXFLQSif0K}

  redis:
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-H733Kdjndks81}

  redis-cache:
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: ${REDIS_CACHE_PASSWORD:-t4Ph722qJ5QHeQ1qfu36}
